 # Version: 0.0.1
   FROM ubuntu:15.10
   MAINTAINER Brian Maher "briancmaher@gmail.com"
   RUN apt-get update 
   RUN apt-get install -y nginx
   RUN echo 'bmaher.com' \
       >/var/www/html/index.nginx-debian.html
   EXPOSE 80
