 # Version: 0.0.1
   FROM ubuntu:15.10
   MAINTAINER Brian Maher "briancmaher@gmail.com"
   RUN apt-get update && apt-get install -y nginx
   RUN echo 'Hi, I am in your container' \
       >/usr/share/nginx/html/index.html
   EXPOSE 80
